# Generated by Django 3.1.14 on 2024-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_hr',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
