# Generated by Django 3.1.14 on 2024-09-26 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240925_1100'),
        ('services', '0003_auto_20240926_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_hr',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('address', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
