# Generated by Django 3.1.14 on 2024-09-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20240926_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
