# Generated by Django 3.1.14 on 2024-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20240927_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
