# Generated by Django 3.1.14 on 2024-10-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20240927_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestservice',
            options={'verbose_name': 'Requested service', 'verbose_name_plural': 'Requested services'},
        ),
    ]
