# Generated by Django 3.1.14 on 2024-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20241005_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
